name: Update Domain for JSON

on:
  push:
    paths:
      - tv/XYQHiker/*.json  # 监控JSON文件夹的变动
  workflow_dispatch:  # 手动触发

jobs:
  update_domain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 您可以选择其他版本

      - name: Install dependencies
        run: |
          pip install requests  # 如果您的 Python 脚本依赖其他库，请在这里添加

      - name: Run Python script to update domain in JSON
        run: |
          python3 update_domain.py  # 运行您的 Python 脚本
