name: Update Domain in JSON

on:
  push:
    branches:
      - main  # 也可以设置为您想触发的分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update-domain:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install requests

      # Step 4: Run Python script to update domain in JSON
      - name: Run update_domain.py
        run: |
          python3 update_domain.py

      # Step 5: Commit and push the updated JSON file back to the repository
      - name: Commit updated JSON
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add path/to/your/json/file.json  # 更新为您的 JSON 文件路径
          git commit -m "Update domain in JSON"
          git push origin main  # 推送到主分支（根据需要修改）
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动使用 GitHub 提供的 token
